project:
  type: website
  output-dir: docs

website:
  title: "Lifecourse GWAS consortium"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - cohorts.qmd
      - resources.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



