project:
  type: website
  output-dir: docs

website:
  title: "Lifecourse GWAS consortium"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cohorts.qmd
      - resources.qmd
  page-footer: |
    ---
    <a href="https://www.bristol.ac.uk/ieu/" target="_blank"><img src="images/mrcieu_bristol.png" width="500"></a>
    


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


